# Generated by Django 3.0.5 on 2023-10-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='add_date',
        ),
    ]
